package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.List<java.lang.String> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList<java.lang.String>(1);
    _jspx_dependants.add("/css/default.css");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.List<java.lang.String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write("Design by Free CSS Templates\r\n");
      out.write("http://www.freecsstemplates.org\r\n");
      out.write("Released for free under a Creative Commons Attribution 2.5 License\r\n");
      out.write("*/\r\n");
      out.write("label, legend {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("fieldset{\r\n");
      out.write("  border: 1px solid rgb(255,232,57);\r\n");
      out.write("  width: 300px;\r\n");
      out.write("  margin-top: 2cm;\r\n");
      out.write("  margin:auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    margin: 0px;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    background: #191919 url(images/bg.gif) repeat left top;\r\n");
      out.write("    text-align: justify;\r\n");
      out.write("    font-family: Tahoma, Arial, Helvetica, sans-serif;\r\n");
      out.write("    font-size: 11px;\r\n");
      out.write("    color: #000000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1, h2, h3 {\r\n");
      out.write("    margin-top: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("    font-size: 1.6em;\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("    font-size: 1.6em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h3 {\r\n");
      out.write("    font-size: 1em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #333333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    a:hover {\r\n");
      out.write("        border-bottom: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    a img {\r\n");
      out.write("        border: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("img.left {\r\n");
      out.write("    float: left;\r\n");
      out.write("    margin: 0 20px 0 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img.right {\r\n");
      out.write("    float: right;\r\n");
      out.write("    margin: 0 0 0 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#header {\r\n");
      out.write("    width: 960px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    /*height: 262px;*/\r\n");
      out.write("    height: 212px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 5px;\r\n");
      out.write("    right: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    #login a {\r\n");
      out.write("        color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("/* Header */\r\n");
      out.write("\r\n");
      out.write("#logo {\r\n");
      out.write("    width: 960px;\r\n");
      out.write("    height: 150px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    /*padding-top: 50px;*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    #logo h1, #logo p {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding-left: 100px;\r\n");
      out.write("        color: #FFFFFF;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #logo span {\r\n");
      out.write("        color: #FFFFFF;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #logo h1 {\r\n");
      out.write("        padding: 25px 0 0 0;\r\n");
      out.write("        letter-spacing: -1px;\r\n");
      out.write("        text-transform: lowercase;\r\n");
      out.write("        font-weight: normal;\r\n");
      out.write("        font-size: 4.8em;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #logo p {\r\n");
      out.write("        padding: 4px 0 0 3px;\r\n");
      out.write("        font-family: Georgia, \"Times New Roman\", Times, serif;\r\n");
      out.write("        font-size: 22px;\r\n");
      out.write("        color: #FFFFFF;\r\n");
      out.write("        font-style: italic;\r\n");
      out.write("        text-decoration: overline;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #logo a {\r\n");
      out.write("        border: none;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: #FFFFFF;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("/* Menu */\r\n");
      out.write("\r\n");
      out.write("#menu {\r\n");
      out.write("    width: 960px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    height: 62px;\r\n");
      out.write("    background: url(images/img02.jpg) repeat-x left top;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    #menu ul {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 24px 0 0 0px;\r\n");
      out.write("        list-style: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #menu li {\r\n");
      out.write("        float: left;\r\n");
      out.write("        display: inline;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #menu a {\r\n");
      out.write("        height: 30px;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 20px 30px 0 30px;\r\n");
      out.write("        background: url(images/img06.jpg) no-repeat right 15px;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("        font-size: 11px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        color: #000000;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("        #menu a:hover {\r\n");
      out.write("            color: #2C5270;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    #menu .current_page_item a {\r\n");
      out.write("        color: #2C5270;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("/* Wrapper */\r\n");
      out.write("\r\n");
      out.write("#wrapper {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin: 0px;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Page */\r\n");
      out.write("\r\n");
      out.write("#page {\r\n");
      out.write("    width: 960px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("    background: url(images/img03.jpg) repeat-y left top;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#page-bg {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Latest Post */\r\n");
      out.write("\r\n");
      out.write("#latest-post {\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    border: 1px solid #E7E7E7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Content */\r\n");
      out.write("\r\n");
      out.write("#content {\r\n");
      out.write("    float: left;\r\n");
      out.write("    width: 460px;\r\n");
      out.write("    margin: 0px 20px 20px 20px;\r\n");
      out.write("    background: #FFFFFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post {\r\n");
      out.write("    padding-bottom: 15px;\r\n");
      out.write("    line-height: 200%;\r\n");
      out.write("    background: url(images/img04.jpg) repeat-x left bottom;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    .post h1 {\r\n");
      out.write("        font-weight: normal;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write(".title {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 30px 0 4px 0px;\r\n");
      out.write("    font-size: 28px;\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    .title a {\r\n");
      out.write("        border-bottom: none;\r\n");
      out.write("        color: #000000;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("        .title a:hover {\r\n");
      out.write("            border-bottom: 1px dotted #000000;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write(".title-medium {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 15px 0 4px 0px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    .title-medium a {\r\n");
      out.write("        border-bottom: none;\r\n");
      out.write("        color: #000000;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("        .title-medium a:hover {\r\n");
      out.write("            border-bottom: 1px dotted #000000;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write(".byline {\r\n");
      out.write("    background: #676767;\r\n");
      out.write("    margin: 10px 0px 20px 0px;\r\n");
      out.write("    padding: 4px 10px;\r\n");
      out.write("    font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("    font-size: 11px;\r\n");
      out.write("    color: #FFFFFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tag {\r\n");
      out.write("    padding: 0 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".entry {\r\n");
      out.write("    padding: 0px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".links {\r\n");
      out.write("    width: 80px;\r\n");
      out.write("    height: 33px;\r\n");
      out.write("    background: url(images/img05.jpg) no-repeat left top;\r\n");
      out.write("    text-align: right;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    .links a {\r\n");
      out.write("        display: block;\r\n");
      out.write("        height: 25px;\r\n");
      out.write("        padding-top: 8px;\r\n");
      out.write("        padding-left: 10px;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        color: #5E5E5E;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("        .links a:hover {\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("p.links a.more {\r\n");
      out.write("    color: #5E5E5E;\r\n");
      out.write("}\r\n");
      out.write("/* Sidebars */\r\n");
      out.write("\r\n");
      out.write("#sidebar1 {\r\n");
      out.write("    float: left;\r\n");
      out.write("    width: 230px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar2 {\r\n");
      out.write("    float: right;\r\n");
      out.write("    width: 230px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar {\r\n");
      out.write("    float: left;\r\n");
      out.write("    border-top: 10px solid #2C5270;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    color: #737373;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    .sidebar ul {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        list-style: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .sidebar li {\r\n");
      out.write("        padding: 0 0 20px 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("        .sidebar li ul {\r\n");
      out.write("            background: none;\r\n");
      out.write("            padding-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar li li {\r\n");
      out.write("            margin: 0px 15px;\r\n");
      out.write("            padding: 8px 0px;\r\n");
      out.write("            border-bottom: 1px #474747 dashed;\r\n");
      out.write("            background: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .sidebar li h2 {\r\n");
      out.write("            height: 26px;\r\n");
      out.write("            background: #0C0C0C;\r\n");
      out.write("            margin: 0 0 0 0;\r\n");
      out.write("            padding: 14px 15px 0px 15px;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            font-size: 11px;\r\n");
      out.write("            font-family: Tahoma, Arial, Helvetica, sans-serif;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: #FFFFFF;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    .sidebar a {\r\n");
      out.write("        color: #BDBDBD;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("/* Search */\r\n");
      out.write("\r\n");
      out.write("#searchform {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0 0 20px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    #searchform br {\r\n");
      out.write("        display: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #searchform h2 {\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("#s {\r\n");
      out.write("    margin: 10px 0px 0 15px;\r\n");
      out.write("    padding: 2px 2px;\r\n");
      out.write("    width: 165px;\r\n");
      out.write("    height: 18px;\r\n");
      out.write("    border: 1px solid #CCCCCC;\r\n");
      out.write("    background: #FFFFFF;\r\n");
      out.write("    font-size: 10px;\r\n");
      out.write("    color: #000000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#x {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 2px 5px;\r\n");
      out.write("    height: 25px;\r\n");
      out.write("    background: #CA8186;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("    font-size: 10px;\r\n");
      out.write("    color: #CCCCCC;\r\n");
      out.write("}\r\n");
      out.write("/* Calendar */\r\n");
      out.write("\r\n");
      out.write("#calendar_wrap {\r\n");
      out.write("    padding: 10px 15px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    #calendar_wrap table {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #calendar_wrap th {\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #calendar_wrap td {\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #calendar_wrap tfoot td {\r\n");
      out.write("        border: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("        #calendar_wrap tfoot td#prev {\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            border: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("            #calendar_wrap tfoot td#prev a {\r\n");
      out.write("                border: none;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        #calendar_wrap tfoot td#next {\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            border: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("            #calendar_wrap tfoot td#next a {\r\n");
      out.write("                border: none;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("/* Footer */\r\n");
      out.write("\r\n");
      out.write("#footer {\r\n");
      out.write("    width: 1000px;\r\n");
      out.write("    height: 80px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    padding: 0 20px;\r\n");
      out.write("    background: url(images/img03.gif) no-repeat center top;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    #footer p {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 10px 0 0 0;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("        font-size: 10px;\r\n");
      out.write("        font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("        color: #737373;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #footer a {\r\n");
      out.write("        color: #BDBDBD;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #footer .link {\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #footer .copyright {\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("/* DND */\r\n");
      out.write("\r\n");
      out.write(".uploadArea {\r\n");
      out.write("    min-height: 300px;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    border: 1px dotted #ccc;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    cursor: move;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    .uploadArea h1 {\r\n");
      out.write("        color: #ccc;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        z-index: 0;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 25px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write(".dfiles {\r\n");
      out.write("    clear: both;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    background-color: #E4E4E4;\r\n");
      out.write("    padding: 3px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    height: 25px;\r\n");
      out.write("    margin: 3px;\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("    width: 97%;\r\n");
      out.write("    opacity: 0.6;\r\n");
      out.write("    cursor: default;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    .dfiles h5 {\r\n");
      out.write("        padding: 0px;\r\n");
      out.write("        margin: 0px;\r\n");
      out.write("        width: 95%;\r\n");
      out.write("        line-height: 25px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dfiles h5, h5 img {\r\n");
      out.write("        float: left;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write(".invalid {\r\n");
      out.write("    border: 1px solid red !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".buttonUpload {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: 4px 10px 4px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);\r\n");
      out.write("    background-color: #0074cc;\r\n");
      out.write("    -webkit-border-radius: 4px;\r\n");
      out.write("    -moz-border-radius: 4px;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    border-color: #e6e6e6 #e6e6e6 #bfbfbf;\r\n");
      out.write("    border: 1px solid #cccccc;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".progress img {\r\n");
      out.write("    margin-top: 7px;\r\n");
      out.write("    /*margin-left: 24px;*/\r\n");
      out.write("    position: absolute;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Login page</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div style=\"color:green\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${system_message }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</div>\r\n");
      out.write("<div style=\"color:red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error_message }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</div>\r\n");
      out.write("<form action=\"/ctrs/login\" method=\"post\">\r\n");
      out.write("\t<fieldset>\r\n");
      out.write("\t\t<legend>Login</legend>\r\n");
      out.write("\t\t<p><label for=\"user_name\">Username:</label><input type=\"text\" name=\"user_name\"/></p>\r\n");
      out.write("\t\t<p><label for=\"password\">Password:</label><input type=\"password\" name=\"password\"/></p>\r\n");
      out.write("\t\t<div></div>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Log in\"/>\r\n");
      out.write("\t\t<a href=\"/ctrs/register\"><button type=\"button\">Register</button></a> \r\n");
      out.write("\t</fieldset>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
